apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: well-known-handler
  name: well-known-handler
  namespace: matrix
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: registry.fedoraproject.org/fedora:30
      name: "30"
      referencePolicy:
        type: Source
