apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: synapse
  namespace: matrix
  labels:
    app: synapse
    service: synapse
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: docker.io/matrixdotorg/synapse:v1.3.1-py3
      name: stable
      referencePolicy:
        type: Local
