apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
    service: synapse
  name: web
  namespace: matrix
spec:
  ports:
    - port: 8008
      protocol: TCP
      targetPort: 8008
  selector:
    deploymentconfig: synapse
  sessionAffinity: None
  type: ClusterIP
