apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    image.openshift.io/triggers: |
      [
        {"from":{"kind":"ImageStreamTag","name":"appservice-irc:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"appservice-irc\")].image"}
      ]
  labels:
    app: synapse
    service: irc-bridge
    server: freenode
  name: appservice-irc-freenode
  namespace: matrix
spec:
  replicas: 1
  selector:
    deploymentconfig: appservice-irc-freenode
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synapse
        service: irc-bridge
        server: freenode
        deploymentconfig: appservice-irc-freenode
    spec:
      containers:
        - image: ""
          imagePullPolicy: Always
          name: appservice-irc
          volumeMounts:
            - mountPath: /config
              name: volume-config
            - mountPath: /data
              name: volume-data
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
            - name: BRIDGE_PORT
              value: "9999"
            - name: APPSERVICE
              value: /config/registration_file.yaml
            - name: APPSERVICE_URL
              value: "http://freenode-bridge:9999"
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 9999
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-config
          secret:
            defaultMode: 420
            secretName: freenode-config
        - name: volume-data
          emptyDir: {}
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - appservice-irc
        from:
          kind: ImageStreamTag
          name: "appservice-irc:latest"
      type: ImageChange
    - type: ConfigChange
