kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: oauth2-cas-proxy
  namespace: matrix
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "oauth2-cas-proxy:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/vrutkovs/oauth2-cas-proxy"
  triggers:
    - type: ConfigChange
  runPolicy: Serial
