namespace: synapse
resources:
  - 01-namespace.yaml
  - synapse/01-imagestream.yaml
  - synapse/02-deploymentconfig.yaml
  - postgres/01-imagestream.yaml
  - postgres/02-pvc.yaml
  - postgres/03-deploymentconfig.yaml
