namespace: matrix
resources:
  - synapse/01-imagestream.yaml
  - synapse/02-deploymentconfig.yaml
  - synapse/03-service.yaml
  - synapse/04-route.yaml
  - postgres/01-imagestream.yaml
  - postgres/02-deploymentconfig.yaml
  - postgres/03-service.yaml
  - riot/01-imagestream.yaml
  - riot/02-deploymentconfig.yaml
  - riot/03-service.yaml
  - riot/04-route.yaml
  - mxisd/01-imagestream.yaml
  - mxisd/02-deploymentconfig.yaml
  - mxisd/03-service.yaml
  - mxisd/04-route.yaml
  - well-known-handler/01-imagestream.yaml
  - well-known-handler/02-deploymentconfig.yaml
  - well-known-handler/03-service.yaml
  - well-known-handler/04-route.yaml
  - oauth2-cas-proxy/01-imagestream.yaml
  - oauth2-cas-proxy/02-buildconfig.yaml
  - oauth2-cas-proxy/03-deploymentconfig.yaml
  - oauth2-cas-proxy/04-service.yaml
  - oauth2-cas-proxy/05-route.yaml
  - appservice-irc-freenode/01-imagestream.yaml
  - appservice-irc-freenode/02-deploymentconfig.yaml
  - appservice-irc-freenode/03-service.yaml
configurations:
  - kustomize-config.yaml
vars:
  - name: SITE_HOSTNAME
    objref:
      kind: Route
      name: well-known-handler
      apiVersion: route.openshift.io/v1
    fieldref:
      fieldpath: spec.host
