namespace: synapse
resources:
  - 01-namespace.yaml
  - synapse/01-imagestream.yaml
  - synapse/02-deploymentconfig.yaml
  - synapse/03-service.yaml
  - synapse/04-route.yaml
  - postgres/01-imagestream.yaml
  - postgres/02-pvc.yaml
  - postgres/03-deploymentconfig.yaml
  - postgres/04-service.yaml
  - riot/01-imagestream.yaml
  - riot/02-deploymentconfig.yaml
  - riot/03-service.yaml
  - riot/04-route.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: matrix-configs
  files:
    - configs/federation-reader.worker
    - configs/homeserver.yaml
    - configs/log.config.yaml
- name: riot-configs
  files:
    - configs/config.json
secretGenerator:
- name: tls-secrets
  files:
  - secrets/signing.key
  - secrets/tls.crt
  - secrets/tls.dh
  - secrets/tls.key
configurations:
- kustomize-config.yaml
vars:
- name: SITE_HOSTNAME
  objref:
    kind: Route
    name: synapse
    apiVersion: route.openshift.io/v1
  fieldref:
    fieldpath: spec.host
