apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: riot
  namespace: synapse
  labels:
    app: synapse
    service: riot
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker.io/bubuntux/riot-web:v1.2.3
    name: stable
    referencePolicy:
      type: Local
