apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: riot
  namespace: matrix
  labels:
    app: synapse
    service: riot
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: docker.io/vrutkovs/riot-nginx:v1.2.3
      name: stable
      referencePolicy:
        type: Local
