apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
    service: riot
  name: riot
  namespace: matrix
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    deploymentconfig: riot
  sessionAffinity: None
  type: ClusterIP
