apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mxisd
  namespace: matrix
  labels:
    app: synapse
    service: mxisd
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker.io/kamax/mxisd:1.4.5
    name: stable
    referencePolicy:
      type: Local
