kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: synapse
  labels:
    app: synapse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
