kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  namespace: matrix
  labels:
    app: synapse
    service: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
