apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
  name: postgresql
  namespace: synapse
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    deploymentconfig: postgresql
  sessionAffinity: None
  type: ClusterIP
